export const BASE_URL = import.meta.env.VITE_API_URL ?? ''

export const API = {
  LOGIN:              '/api/v1/auth/login',
  ME:                 '/api/v1/auth/me',
  RECOVER_PASSWORD:   '/api/v1/auth/recover-password',
  RESET_PASSWORD:     '/api/v1/auth/reset-password',

  PERSONS:                      '/api/v1/persons/',
  PERSONS_DOCUMENT_TYPES:       '/api/v1/persons/document/available',
  PERSONS_GENDERS:              '/api/v1/persons/genders/available',

  EMPRESAS:         '/api/v1/companies/',
  TERMS_PUBLIC:     '/api/v1/terms/public',
  TERMS:            '/api/v1/terms',
  CARGOS:           '/api/v1/cargos',
  USUARIOS:         '/api/v1/users/',
  USERS_VERIFY:     '/api/v1/users/verify',
  ROLES:            '/api/v1/roles',
  ROLES_PUBLIC:     '/api/v1/roles/public',
  CONTRATOS:                  '/api/v1/contratos',
  ESTABLISHED_CONTRACTS:      '/api/v1/established_contracts/',
  ESTABLISHED_INCREASES:      '/api/v1/established_increases',
  ESTABLISHED_DEDUCTIONS:     '/api/v1/established_deductions',
  ESTABLISHED_SCHEDULES:      '/api/v1/established_schedules',
  EMPLOYEE_CHARGES_PUBLIC:    '/api/v1/employee_charges/public',
  EMPLOYEES:        '/api/v1/employees/',
  COMPANIES_PUBLIC: '/api/v1/companies/public',
  CONTRACTS:            '/api/v1/contracts/',
  CONTRACTS_FILTERED:   '/api/v1/contracts/filtered',
  DASHBOARD_STATS:      '/api/v1/contracts/dashboard/statistics',
  INCREASES:        '/api/v1/increases',
  DEDUCTIONS:       '/api/v1/deductions',
  SCHEDULES:        '/api/v1/schedules',
  SOLICITUDES:      '/api/v1/solicitudes',
  NOTIFICACIONES:       '/api/v1/notificaciones',
  NOTIFICATIONS:        '/api/v1/notifications/me',
  NOTIFICATIONS_UNREAD: '/api/v1/notifications/me/unread-count',
  CHATBOT:          '/api/v1/chatbot/terminos',
}
